version: '3.3'
services:

  local-postgres:
    build:
      context: ./db
      dockerfile: localdb.Dockerfile
    container_name: local-postgres-db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - postgres_db:/var/lib/postgresql/data

  local-minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_storage:/local_minio_data
    command: server --console-address ":9001" /local_minio_data

##scheduler_api:
##  build:
##    context: ../src/ingestion_scheduler
##  container_name: scheduler_api
##  restart: always
##  environment:
##    - POSTGRES_USER=${POSTGRES_USER}
##    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
##    - MINIO_ROOT_USER=${MINIO_ROOT_USER}
##    - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
##  volumes:
##    - ../src/ingestion_scheduler:/usr/src/app
##  ports:
##    - "3001:3001"

  unified_diff_api:
    build:
      context: ../src/file_compare
    container_name: unified_diff_api
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - ../src/file_compare/main.py:/app/main.py
    ports:
      - "8000:8000"

volumes:
  postgres_db:
  minio_storage: 