version: '3.3'
services:

  local-postgres:
    build:
      context: ./db
      dockerfile: localdb.Dockerfile
    container_name: local-postgres-db
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - '5432:5432'
    volumes:
      - postgres_db:/var/lib/postgresql/data

  local-minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=adminroot
      - MINIO_ROOT_PASSWORD=adminroot
    volumes:
      - minio_storage:/local_minio_data
    command: server --console-address ":9001" /local_minio_data

volumes:
  postgres_db:
  minio_storage: 